spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true

jwt:
  secret: SECRET
  expiration_in_ms: 86400000